cleanup scripts to support osx
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

diff --git a/bin/enable_webcam b/bin/enable_webcam
--- a/bin/enable_webcam
+++ b/bin/enable_webcam
@@ -1,3 +1,9 @@
 #!/bin/sh
 
+OS=`uname -s`
+if [ "$OS" = "Darwin" ]; then
+	echo "ERROR: This script is not supported on Mac OS X"
+	exit 1
+fi
+
 sudo rm /etc/modprobe.d/disable_webcam.conf
diff --git a/bin/urun b/bin/urun
--- a/bin/urun
+++ b/bin/urun
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+OS=`uname -s`
+if [ "$OS" = "Darwin" ]; then
+	echo "ERROR: This script is not supported on Mac OS X"
+	exit 1
+fi
+
 function isCharging(){
 	batteryStatus=$(cat /sys/class/power_supply/BAT0/status)
 	
